[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
delegation_program = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
inco_lightning = "5sjEbPiqgZrYwR31ahR6Uk9wf5awoX61YGg7jExQSwaj"
payroll = "CgRkrU26uERpZEPXUQ2ANXgPMFHXPrX4bFaM5UHFdPEh"

[programs.localnet]
payroll = "CgRkrU26uERpZEPXUQ2ANXgPMFHXPrX4bFaM5UHFdPEh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keys/payroll-authority.json"

[scripts]
test = "echo 'No legacy root tests configured. Use app/scripts and keeper runbook checks.'"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://devnet.helius-rpc.com/?api-key=06227422-9d57-42de-a7b3-92f1491c58af"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "USD1111111111111111111111111111111111111"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "5sjEbPiqgZrYwR31ahR6Uk9wf5awoX61YGg7jExQSwaj"

[[test.validator.clone]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
